### ISSUE TITLE
Am i able to map ZR to a mouse wheel/scroll? 

### ISSUE THREAD

**Issue by footfoot19** [Maschell/controller_patcher_configs#20]
If so, whats the term for it? All i can find is "LEFT_CLICK" AND "RIGHT_CLICK" and its gonna be a pain trying to guess the MOUSE_SCROLL_UP/MOUSE_SCROLL_DOWN term (oh god is it really that and i am just wasting peoples time?)

**Comment by Maschell** [comment]
The mouse wheel is currently not supported

**Comment by footfoot19** [comment]
Edit: I'm starting to realize im making quite a ridiculous request as i dive deeper and understand more about how all this works. Will surrender by closing this issue.

Ah, if i can't do that. Can you help me understand how to use a network USB mouse instead? I managed to get my xbone controller to work (as proof that i have a grasp on what to do). But i am stumped at trying to make this mouse register as a HID-like device. It shows up network client list. But even after making a config file, it doesn't seem to recognize it.

For brevity sake, i plan on using autoclicking software to make my mouse click in very specific ways (thus, pressing in-game buttons in certain ways and speeds. Not possible since scroll wheel isnt an option with native support)

**Comment by Maschell** [comment]
This may help you:
https://github.com/QuarkTheAwesome/HIDtoVPADNetworkClient/issues/11#issuecomment-292778879
