### ISSUE TITLE
Switch pro controller not responding with HID to VPAD

### ISSUE THREAD

**Issue by masterspike52** [Maschell/controller_patcher_configs#23]
ive plugged in the pro controller via usb in both ports on the front of the wii u but HID to VPAD isnt recognizing it as a controller. Not going to rule out that its the controller but id like to not jump to that conclusion

**Comment by masterspike52** [comment]
learned its not a pro controller but a plus wired controller

**Comment by ToiletSoldier** [comment]
I plugged in my switch pro controller into my wii u and it’s not responding. Do you have an anwser to this?

**Comment by masterspike52** [comment]
You probably need to make a new configuration for it, it was the fix for
the issue I had with my switch core plus controllee

**Comment by jke05** [comment]
Hi @masterspike52 It's me @ToiletSoldier on a different account. Do I have to download a switch pro controller config file or make it myself? If I do, which one do I download , and, if not, where do I learn to make one because i'm clueless about making config files.

**Comment by masterspike52** [comment]
Hey there, I was in the same boat at one point, there should be one
pre-made with this you just have to get them from
https://github.com/Maschell/controller_patcher_configs and then if you
wanna make one you have to use this wiki
https://github.com/Maschell/controller_patcher/wiki and it should tell you
how to do it

**Comment by jke05** [comment]
I've tried the pre-made one and it won't work. While with trying to make one, I couldn't understand anything and got confused. I'm sorry if i'm troubling you.
